version: "3"

set: [pipefail, errexit, nounset]

vars:
  TWIPI_URL: "http://localhost:8080"
  PORT: 8000

tasks:
  default:
    deps: [dev]

  dev:
    deps: [generate]
    env:
      VITE_TWIPI_URL: "{{ .TWIPI_URL }}"
    cmds:
      - vite --clearScreen=false --port="$PORT"

  build:
    deps: [generate]
    env:
      VITE_TWIPI_URL: https://twipi.libdb.so
    cmds:
      - vite build

  generate:
    deps: [generate-ts-proto]

  generate-ts-proto:
    watch: true
    requires:
      vars: [PROTO_PATH]
    status:
      - grep -q "$PROTO_PATH" "$TASK_TEMP_DIR"/proto_path
    cmds:
      - for:
          var: PROTO_PATH
          split: ":"
        cmd: |
          protoc -I={{ shellQuote .ITEM }} \
            --plugin=node_modules/.bin/protoc-gen-ts_proto \
            --ts_proto_opt=esModuleInterop=true \
            --ts_proto_opt=importSuffix=.js \
            --ts_proto_out=src/lib/proto \
            {{ shellQuote .ITEM }}/*.proto
      - prettier -w src/lib/proto
      - echo "$PROTO_PATH" > "$TASK_TEMP_DIR"/proto_path
    generates:
      - src/lib/proto/*.ts
