version: "3"

set: [pipefail, errexit, nounset]

vars:
  TWIPI_URL: '{{ .TWIPI_URL | default "http://localhost:8080" }}'
  PORT: '{{ .PORT | default "3000" }}'

tasks:
  default:
    deps: [dev]

  dev:
    deps: [node_modules, generate]
    env:
      VITE_TWIPI_URL: "{{ .TWIPI_URL }}"
    cmds:
      - echo "Using $VITE_TWIPI_URL for the Twipi URL."
      - vite --clearScreen=false --port="$PORT"

  build:
    deps: [node_modules, generate]
    env:
      VITE_TWIPI_URL: https://twipi.libdb.so
    cmds:
      - vite build

  generate:
    deps: [generate-ts-proto]

  generate-ts-proto:
    watch: true
    requires:
      vars: [PROTO_PATH]
    status:
      - grep -q "$PROTO_PATH" "$TASK_TEMP_DIR"/proto_path
    deps: [node_modules]
    cmds:
      - for:
          var: PROTO_PATH
          split: ":"
        cmd: |
          protoc -I={{ shellQuote .ITEM }} \
            --plugin=node_modules/.bin/protoc-gen-ts_proto \
            --ts_proto_opt=esModuleInterop=true \
            --ts_proto_opt=importSuffix=.js \
            --ts_proto_out=src/lib/proto \
            {{ shellQuote .ITEM }}/*.proto
      - prettier -w src/lib/proto
      - echo "$PROTO_PATH" > "$TASK_TEMP_DIR"/proto_path
    generates:
      - src/lib/proto/*.ts

  node_modules:
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules
